---
abstract: 'tiny implementation of finite state machine'
author:
  - '<Taiyoh Tanaka> <<sun.basix@gmail.com>>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
  Test::Requires: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: FSM::Tiny
name: FSM-Tiny
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Lite: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/taiyoh/p5-FSM-Tiny.git
version: 0.03
